__version__: 0.4.5
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.RandomRotate90
    always_apply: false
    p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.HorizontalFlip
    always_apply: false
    p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.Transpose
    always_apply: false
    p: 0.5
  - __class_fullname__: albumentations.augmentations.transforms.RandomCrop
    always_apply: false
    height: 56
    p: 1.0
    width: 56
