__version__: 1.1.0
transform:
  __class_fullname__: albumentations.core.composition.Compose
  additional_targets: {}
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: albumentations.augmentations.transforms.Normalize
    mean: [0.4802, 0.4481, 0.3975]  # Tiny Imagenet stats
    std: [0.2302, 0.2265, 0.2262]
    max_pixel_value: 255
    always_apply: true
    p: 1
  - __class_fullname__: albumentations.pytorch.transforms.ToTensorV2
    always_apply: true
    p: 1